### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by jos3s** [ELowry/StadiaIcons#1]
Hi, I would like to ask if you could make the icon for Uno, Serius Sam 4 and Baldur's Gate 3? All before the release date, Uno seems to come out on the 15th of that month, Serius Sam 4 on the 24th and BG3 on the 30th, I have a profile on twitter (DeOlhoNoStadia) to post news about Stadia and use your icons for these releases would be great

**Comment by ELowry** [comment]
Hi there!
Sure, I'll have a go at those, shouldn't take too long.
I'll keep you updated as soon as they're ready =)

**Comment by ELowry** [comment]
There you go, I've added all 3 titles!

**Comment by jos3s** [comment]
Thank you!
