### ISSUE TITLE
Game name cut off for Assassin's Creed games

### ISSUE THREAD

**Issue by DanieleS** [ELowry/StadiaIcons#7]
When I create a shortcut for an Assassin's Creed game on MacOS, the shortcut name is something like `Assassin&`.
This happens for both games of the series.

![image](https://user-images.githubusercontent.com/3601911/102109554-76f63300-3e34-11eb-8ccc-0a8f38050aec.png)

~~Not sure if this is a MacOS only issue, later I'll try with Windows too.~~

Same issue on Windows.

![image](https://user-images.githubusercontent.com/3601911/102110915-06e8ac80-3e36-11eb-9b24-23e4e1e6044e.png)

**Comment by ELowry** [comment]
Hi there!

I have a rough idea of what's happening, but just to make sure I don't go chasing bugs in the wrong place, did you get the shortcuts through https://stadiaicons.web.app or using the Stadia Enhanced extension?

**Comment by DanieleS** [comment]
Hi, I got the shortcut directly through https://stadiaicons.web.app

**Comment by DanieleS** [comment]
Ok, I can reproduce the same issue on Windows too. I'll update this issue accordingly.

**Comment by ELowry** [comment]
Should be fixed!

I'll make sure to do a bit of testing over the next 10–20 minutes, and you might want to clear the game list page's cache (`Ctrl+F5`).
Unfortunately, I'm pretty sure you'll need to recreate the shortcuts though :/

**Comment by ELowry** [comment]
Fixed!

That was a mess ^^'
