### ISSUE TITLE
DOOM (2016) is missing icon

### ISSUE THREAD

**Issue by bgiesing** [ELowry/StadiaIcons#8]
DOOM (2016) says "Unfortunately the icons for this game is not yet available." despite appearing inside the icon list in the repo and also doesn't appear at all in the games list on the StadiaIcons Shortcut homepage (only managed to get to it because the StadiaEnhanced extension linked to it https://stadiaicons.web.app/cc1a8e0e94d54f15a22149fed93bbd7arcp1/?fullName=DOOM )

**Comment by ELowry** [comment]
Should be fixed now =)
